# app.yaml

runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: production
  SECRET_KEY: your_secret_key_here
  DATABASE_URL: sqlite:///books.db

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
